### ISSUE TITLE
Remove/Change Google Analytics

### ISSUE THREAD

**Issue by dcbroad3** [ShadowTheAge/factorio-lab#2]
Could you remove the Google analytics tag, or change it? My analytics for factoriolab show a 10x+ user spike this week and it took me longer than I'd like to admit to figure out that it's all from this branch. 😳

**Comment by ShadowTheAge** [comment]
Uh, sorry about that, I'll do that when I get home

**Comment by ShadowTheAge** [comment]
By the way, If you would like to "officially" support Dyson Sphere program (through base set or something like that) I can direct users to your "official" version, and give c# tools/instructions I used to generate the data and icons.

However, the game is rather different and will probably change during its early access a lot. Current data format does not work with mods at all and when they add mod support it will change.

I didn't know that this fork (and Dyson Sphere Program) will become this popular. I did the fork on the day it came into early access and it wasn't apparent.

**Comment by ShadowTheAge** [comment]
I am not familiar with angular and have only basic javascript knowledge, is removing

```
<!-- Global site tag (gtag.js) - Google Analytics -->
    <script
      async
      src="https://www.googletagmanager.com/gtag/js?id=G-TFR5Z43GPH"
    ></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag() {
        dataLayer.push(arguments);
      }
      gtag('js', new Date());

      gtag('config', 'G-TFR5Z43GPH');
    </script>
```
sufficient?

If yes, I have updated the gh-pages

**Comment by dcbroad3** [comment]
Thanks! I think that should do it. At some point I'll try to look into what it would take to have factoriolab directly support DSP. From what you've done here it certainly seems feasible.

**Comment by dcbroad3** [comment]
@ShadowTheAge Factorio Lab now natively supports DSP using the icons.png and (with slight modifications) the data.json you created.
https://factoriolab.github.io/list#s=dsp

I am not a DSP player so do with this what you wish. 😄 The data set for DSP is much smaller than Factorio's so I can likely support it even if I have to do some things manually.

**Comment by ShadowTheAge** [comment]
The question is are you going you support it? If yes, It would be good to make some minor adjustements (maybe activated by the flag in the data.json?) and then how to redirect people to your version

Adjustements:
* I have just updated data.json to make mining numbers precise. They were not before and now they are not in your version. Due to differences in mining, I made that each ore is mined "by its vein". In DSP the amount of veins covered by a miner determines mining speed (linearly)
* It is better to hide columns: Wagons, Beacons, Pollution. Either with the flag in the data.json, or you can hide wagons for example if there are none in the pack. Same for beacons. I saw you have conditional column show but even hidden columns were throwing errors so I removed them completely in my fork.
* I see you added power. I didn't do that because I wasn't able to get it automatically. But ofc I could hardcode it in the script, I just didn't do that. That should remain ofc.

About settings:
* Difficulty has no meaning
* Chemical fuel only matters for generating power (ie there are no burner factories) but it exists.
* Pipe flow rate - all items and fluids are transferred by conveyors BUT that may change in the future as there is a concept for liquid and liquids and items are a little different.
* Inserters are more complicated than in Factorio. But I don't know what "Inserter target" affects. In DSP inserters have travel speed and the transfer speed depends on the distance to the belt. There are also stack inserters and research for it.
* Mining productivity also exists in DSP BUT it does not gives you more ore (just decreases vein usage). However, "Mining speed" exists instead that basically has the meaning of "productivity" in Factorio.
* Research speed also exists and it is infinite research (judging by icon... I didn't get to there to find if it is actually infinite). Each research increases reseach speed by 100% additively (1-2-3-4 not 1-2-4-8)

My bugs:
* When I were exporting data, I didn't get to later factories and set so these recipes are produced by the assembler. That is incorrect and should be fixed. There is also one building with crafting mechanics not present in Factorio. Probably could be simulated if we allow belts to be crafters with their speed equal crafting speed.
* Probably a good idea to disable some recipes by default (that uses rare resources not present in the starting solar system)

About updating data.json
* I can make pull requests for example. BUT for that I need my export script to output data.json that does not require to be modified, and for that I need to know what else to put there. I were also not intending to support the game forever, just for some time before someone else makes a proper calculator.
* I can only automatically fetch recipes and items, and semi-automatically fetch icons. I can't automatically fetch meta data (factory speed and energy usage, belt speed)

About redirecting users:
* I think the best way is to put big notification on my fork that states that FactorioLab now have DSP support and link. Plus a message that my fork will stop working at some date (like a week after that appears).

**Comment by dcbroad3** [comment]
I do plan to fully support it, I will likely add code to distinguish dsp and do things like hide the pollution/wagons/beacons columns. I don't own the game though so at least for now I would rely on others to update data and let me know if things are incorrect. 

I'll write up issues later for the things you brought up.

**Comment by ShadowTheAge** [comment]
At least until they change data format I can update data.json through pull requests. But I need list of things that I need to add to data.json so it will become fully compliant.

Edit: also is there an ability to add recipe name? So that alternate recipes wouldn't have a name like "R39"
